### ISSUE TITLE
when i add check login pipeline, how to recognize this.userId is string?

### ISSUE THREAD

**Issue by welkinwong** [zodern/meteor-relay#20]
```ts
createPublication({
  schema: ...,
}).pipeline(
  function (input, pipeline) {
    if (!this.userId) pipeline.stop();

    return { ...input };
  },
  function (input) {
    this.userId
    // ^^^^^^^^
    // (property) Subscription.userId: string | null
    // but this userId should be string
  }
)
```

I add check login pipeline, this.userId should be string exclude null 😊

**Comment by zodern** [comment]
I don't have a good solution for this. As far as I know, there isn't a way for typescript to know that userId is now defined in the subsequent pipeline steps.

A few ideas:
1. You can add userId to input after checking it. I personally probably wouldn't do this, since normally you don't trust user id's sent by the client, and it would confuse that.
2. You could have a helper to get the userId in each step:
```
// getUserId can throw an error or return a string
let userId = getUserId(this);
```
3. This is common enough we probably could add an option to relay to require there to be a user, and have the proper types.
